import Joi from 'joi';

export const HrDefenderSheetSchema = Joi.object().keys({
  id: Joi.string().required(),
  country: Joi.string().required(),
  threatType: Joi.string().required(),
  location: Joi.string().required(),
  originTown: Joi.string().required(),
  threatOtherType: Joi.string().required(),
  rightsViolatedType: Joi.string().required(),
  rightsViolatedOtherType: Joi.string().required(),
  responseType: Joi.string().required(),
  relationShipCOVIDType: Joi.string().required(),
  relationShipCOVIDOtherType: Joi.string().required(),
  threatAuthor: Joi.string().required(),
  factsReported: Joi.string().required(),
  informationSource: Joi.string().required(),
  informationSourceOther: Joi.string().required(),
  indicateMeans: Joi.string().required(),
  thereWasLegalAction: Joi.string().required(),
  thereWasAndAnswered: Joi.string().required(),
  defenderName: Joi.string().required(),
  UTMCoordinates: Joi.string().required(),
  contactDetails: Joi.string().required(),
  communityBase: Joi.string().required(),
  completedBy: Joi.string().required(),
  personName: Joi.string().required(),
  requestCountry: Joi.string().required(),
  requestType: Joi.string().required(),
  requestAuthor: Joi.string().required(),
  requestNumber: Joi.string().required(),
  toWhomWasRequested: Joi.string().required(),
  requestDescription: Joi.string().required(),
  requestShortDescription: Joi.string().required(),
  reportingCommunityBase: Joi.string().required(),
  organizationName: Joi.string().required(),
  organizationPersonName: Joi.string().required()
});
