services:
  Apps.CoicaSat.controllers.RecoverPasswordPostController:
    class: ../../../controllers/RecoverPassword/RecoverPasswordPostController
    arguments: [ "@CoicaSat.RecoverPassword.application.RecoverPasswordCreator" ]
