services:
  Apps.CoicaSat.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.CoicaSat.controllers.UserProfilePutController:
    class: ../../controllers/UsersProfile/UserProfilePutController
    arguments: [ "@CoicaSat.UsersProfile.application.UserProfileCreator" ]

  Apps.CoicaSat.controllers.UserPostController:
    class: ../../controllers/Users/UserPostController
    arguments: [ "@CoicaSat.Users.application.UserCreator" ]

  Apps.CoicaSat.controllers.UserDeleteController:
    class: ../../controllers/Users/UserDeleteController
    arguments: [ "@CoicaSat.Users.application.UserRemover" ]

  Apps.CoicaSat.controllers.LoginPostController:
    class: ../../controllers/UsersLogin/LoginPostController
    arguments: [ "@CoicaSat.UsersLogin.application.UserAuthenticator" ]

  Apps.CoicaSat.controllers.UserGetController:
    class: ../../controllers/Users/UserGetController
    arguments: [ "@CoicaSat.Users.application.UserFinder" ]

  Apps.CoicaSat.controllers.TokenVerificationGetController:
    class: ../../controllers/TokensVerification/TokenVerificationGetController

  Apps.CoicaSat.controllers.PostPostController:
    class: ../../controllers/Posts/PostPostController
    arguments: [ "@CoicaSat.Posts.application.PostCreator" ]

  Apps.CoicaSat.controllers.PostPutController:
    class: ../../controllers/Posts/PostPutController
    arguments: [ "@CoicaSat.Posts.application.PostCreator" ]

  Apps.CoicaSat.controllers.PostGetController:
    class: ../../controllers/Posts/PostGetController
    arguments: [ "@CoicaSat.Posts.application.PostFinder" ]

  Apps.CoicaSat.controllers.PostDeleteController:
    class: ../../controllers/Posts/PostDeleteController
    arguments: [ "@CoicaSat.Posts.application.PostRemover" ]

  Apps.CoicaSat.controllers.HRDefenderSheetPutController:
    class: ../../controllers/HRDefendersSheets/HRDefenderSheetPutController
    arguments: [ "@CoicaSat.HRDefendersSheets.application.HRDefenderSheetCreator" ]

  Apps.CoicaSat.controllers.HRDefenderSheetPostController:
    class: ../../controllers/HRDefendersSheets/HRDefenderSheetPostController
    arguments: [ "@CoicaSat.HRDefendersSheets.application.HRDefenderSheetCreator" ]

  Apps.CoicaSat.controllers.HRDefenderSheetDeleteController:
    class: ../../controllers/HRDefendersSheets/HRDefenderSheetDeleteController
    arguments: [ "@CoicaSat.HRDefendersSheets.application.HRDefenderSheetRemover" ]

  Apps.CoicaSat.controllers.HRDefenderSheetGetController:
    class: ../../controllers/HRDefendersSheets/HRDefenderSheetGetController
    arguments: [ "@CoicaSat.HRDefendersSheets.application.HRDefenderSheetFinder" ]

imports:
  - { resource: ./ApplicationForMonitoring/application.yaml }

