services:
  CoicaSat.Posts.domain.PostRepository:
    class: ../../../../../Contexts/CoicaSat/Posts/infrastructure/persistence/MongoPostRepository
    arguments: ['@Shared.CoicaSat.ConnectionManager']

  CoicaSat.Posts.application.PostCreator:
    class: ../../../../../Contexts/CoicaSat/Posts/application/PostCreator
    arguments: ['@CoicaSat.Posts.domain.PostRepository']

  CoicaSat.Posts.domain.PostMapper:
    class: ../../../../../Contexts/CoicaSat/Posts/infrastructure/mappers/PostMapper

  CoicaSat.Posts.application.PostRemover:
    class: ../../../../../Contexts/CoicaSat/Posts/application/PostRemover
    arguments: [ '@CoicaSat.Posts.domain.PostRepository' ]

  CoicaSat.Posts.application.PostFinder:
    class: ../../../../../Contexts/CoicaSat/Users/application/UserFinder
    arguments: [ '@CoicaSat.Posts.domain.PostRepository', '@CoicaSat.Posts.domain.PostMapper' ]
