services:
  CoicaSat.Users.domain.UserRepository:
    class: ../../../../../Contexts/CoicaSat/Users/infrastructure/persistence/MongoUserRepository
    arguments: ['@Shared.CoicaSat.ConnectionManager']

  CoicaSat.Users.domain.EncryptionService:
    class: ../../../../../Contexts/CoicaSat/Users/infrastructure/security/Bcrypt/BcryptEncryptionService

  CoicaSat.Users.application.UserCreator:
    class: ../../../../../Contexts/CoicaSat/Users/application/UserCreator
    arguments: ['@CoicaSat.Users.domain.UserRepository', '@CoicaSat.Users.domain.EncryptionService']

  CoicaSat.Users.domain.UserMapper:
    class: ../../../../../Contexts/CoicaSat/Users/infrastructure/mappers/UserMapper

  CoicaSat.Users.application.UserRemover:
    class: ../../../../../Contexts/CoicaSat/Users/application/UserRemover
    arguments: [ '@CoicaSat.Users.domain.UserRepository' ]

  CoicaSat.Users.application.UserFinder:
    class: ../../../../../Contexts/CoicaSat/Users/application/UserFinder
    arguments: ['@CoicaSat.Users.domain.UserRepository', '@CoicaSat.Users.domain.UserMapper']

  CoicaSat.Users.application.UserByIdFinder:
    class: ../../../../../Contexts/CoicaSat/Users/application/UserByIdFinder
    arguments: [ '@CoicaSat.Users.domain.UserRepository']

