services:
  Apps.CoicaSat.controllers.HRDefenderSheetHistoryGetController:
    class: ../../../controllers/HRDefendersSheetsHistory/HRDefenderSheetHistoryGetController
    arguments: [ "@CoicaSat.HRDefendersSheetsHistory.application.HRDefenderSheetHistoryFinder" ]
