imports:
  - { resource: ./Shared/application.yaml }
  - { resource: ./apps/application.yaml }
  - { resource: ./UsersProfile/application.yaml }
  - { resource: ./Users/application.yaml }
  - { resource: ./UsersLogin/application.yaml }
  - { resource: ./Posts/application.yaml }
  - { resource: ./HRDefendersSheets/application.yaml }
  - { resource: ./ApplicationsForMonitoring/application.yaml }
  - { resource: ./HRDefendersSheetsHistory/application.yaml }
